cryostatio/cryostat-agent

- README.md
- pom.xml
- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/RegistrationException.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/resources/META-INF/microprofile-config.properties
Based on #9
Depends on #9
Fixes #11
- feat(jwt): implement JWT flow
- chore(vertx): remove vertx dependency
> fix(vertx): remove vertx dependency

- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/HttpException.java
Fixes #15
To test, I have two possible procedures. The first is the way I accidentally noticed this behaviour. Run the Cryostat `smoketest.sh` and put the laptop to sleep for a while with everything spun up and running. The default discovery ping period is 5 minutes, but the `CRYOSTAT_DISCOVERY_PING_PERIOD` variable can be set to reduce that time for faster testing cycles. Put the host machine to sleep for at least the ping period, then awaken the machine again and check the logs. The Cryostat logs should reflect that it is responding `401` to the agent(s) because their JWTs are expired. Before this PR this will continue repeating. After this PR, the agents should see the first 401 and react by refreshing their registration, so no subsequent 401s should occur.
To simplify that testing …
> fix(registration): handle 401 on update with reregistration

- .github/workflows/ci.yaml
- .github/workflows/maven-publish.yaml
- pom.xml
Replaces #17
Related to https://github.com/cryostatio/cryostat-core/issues/92
Consume `cryostat-core` from GitHub Packages Maven repository. Released versions of `-core` built by CI can be pulled and use as dependency for builds. This requires a GH pkgs authentication token secret to be configured in the repository secrets. Pull requests from forks will not be passed this token and so CI will fail on them - this means that all PRs in this repo, and any others that consume dependencies in this way, need to be created from upstream branches, not fork branches. See #4 vs #19.
> build(pom): pull -core dep from GitHub Packages

- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/Harvester.java
- src/main/java/io/cryostat/agent/Registration.java
Fixes #28
- fix(registration): do not restart harvester on refresh
- ignore start request if already started
- log template and period on start
- fixup! fix(registration): do not restart harvester on refresh
> fix(registration): do not restart harvester on refresh

- src/main/java/io/cryostat/agent/CryostatClient.java
Fixes #49
Previously the form value for `max-files` was encoded as the actual 32-bit bytes of the `int` field. It should actually be encoded as the bytes for a UTF-8 string that can be parsed into the `int` value. Otherwise, the server fails to process this field and the request is rejected.
> fix(max-files): encode value as string, not raw int bytes

- pom.xml
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
Fixes #54
Replaces the JDK HTTP Client with Apache HTTP Client. This is a more robust and easier to use library, and also fixes the above bug.
To test:
1. `mvn install` to get the JAR into local mvn repo
2. `cd quarkus-test ; ./mvnw package && podman build -t quay.io/andrewazores/quarkus-test:latest -f src/main/docker/Dockerfile.jvm . ; podman image prune -f` to build a `quarkus-test` using this updated agent JAR
3. `cd cryostat ; sh smoketest.sh` to run the smoketest setup. `quarkus-test-agent-{0,1,2}` should spin up, each using the new Agent JAR containing this change. `0` should fail to register itself due to a missing environment variable, but the host application should run as usual. `1` should register itself successfully and then periodically push harvested JFR files. `2` should …
> fix(http): use Apache HTTP client

- pom.xml
- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/resources/META-INF/microprofile-config.properties
Fixes https://github.com/cryostatio/cryostat-agent/issues/63
Depends on https://github.com/cryostatio/cryostat/pull/1377 (so the backend knows how to pass the challenge)
~~In this PR the Agent generates Basic auth credentials to secure its built-in HTTP webserver. Incoming HTTP requests to the webserver must pass an HTTP Basic Authentication challenge. The credentials use a fixed username and a randomly generated password string. The password string is held in memory only long enough for the Agent to complete registration and publication of itself to the Cryostat backend. After that point, the password is blanked out from memory and only a hash of the password retained to compare against incoming HTTP requests. This PR also causes the Agent to prefer to register itself with the HTTP Agent …
> feat(plugin): require HTTP Basic authentication

- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/java/io/cryostat/agent/remote/MBeanContext.java
- src/main/java/io/cryostat/agent/remote/RemoteContext.java
- src/main/java/io/cryostat/agent/remote/RemoteModule.java
Fixes #79
See https://github.com/cryostatio/cryostat/pull/1415
This does some refactoring, and then adds a capability for remote clients (the Cryostat server most likely) to retrieve select MBean metrics data over the HTTP API. This requires the same authentication as the discovery plugin flow.
> feat(api): remote readonly accesses

- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/Harvester.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/resources/META-INF/microprofile-config.properties
- fix(registration): check if credentials already exist before submitting
- fix(registration): check and retry registration on slow cadence
- extract registration (re)check config property
Fixes #85
Depends on https://github.com/cryostatio/cryostat/pull/1425
> fix(registration): registration checks and re-registration flow

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/Harvester.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/resources/META-INF/microprofile-config.properties
- add configs for periodic maxage and maxsize
- null out field on state transition
- split between dedicated thread and worker pool
Fixes #95
Depends on #99
Adds two new config parameters for the maxage/maxsize JFR properties. These two properties could already be controlled previously for recordings that are uploaded when the host JVM is exiting, but periodically pushed recordings would always push the entire available JFR repository contents. It's likely that this results in overlapping recording chunks being pushed to the server frequently, wasting network bandwidth and storage capacity. The new config parameters can be tuned to minimize this waste. The maxsize is not applied by default, but the maxage is, and the default data age is taken as 1.5x the harvester period. This will result …
> fix(periodic): config for maxage/maxsize to prevent recording upload timeouts due to large filesize

- README.md
> docs(readme): document registration.prefer-jmx variable

- pom.xml
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/WebServer.java
Fixes #133
This simply changes the matchExpression that the Agent uses when it stores credentials in the Cryostat server's encrypted keyring.
Previously the matchExpression used would be set to match the target's JVM ID. As outlined in the original issue, this would cause problems for target applications with JMX authentication enabled, since the credentials stored by the Agent would match the same target, but are the wrong credentials for that connection.
It does not actually matter what the matchExpression of these stored credentials is because there is a custom subprotocol in use by the Agent and the Cryostat server, so the Cryostat server will always use the correct stored credentials given the correct ID for the Agent it is trying to connect to over HTTP. The matchExpression is …
> fix(credentials): store credentials with non-conflicting matchExpression

- .github/workflows/ci.yaml
Fixes #126
Not sure if it works because my fork doesn't own a gh repo token that is authenticated for use for pulling a `-core` dependency - does the fix make sense?
> ci(secrets): allow ci to use gh package secrets

- .mergify.yml
Related #126 
Related #151
Forgot to put in the mergify configuration to automatically add the label if the pr author is a member of @cryostatio/reviewers.
> ci(mergify): add mergify config for `safe-to-test` label

- .github/workflows/ci.yaml
Related to #149
Related to #151 
Added a check to run CI job only upstream since forks will likely be missing secrets. This avoid CI fail notifications and reduce github use.
> chore(ci): skip CI run on forks

- src/main/java/io/cryostat/agent/Registration.java
> fix(registration): correctly annotate with JMX port number

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/java/io/cryostat/agent/remote/EventTemplatesContext.java
- src/main/java/io/cryostat/agent/remote/EventTypesContext.java
- src/main/java/io/cryostat/agent/remote/MBeanContext.java
- src/main/java/io/cryostat/agent/remote/MutatingRemoteContext.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
- src/main/resources/META-INF/microprofile-config.properties
Fixes #163
Fixes #164
Depends on https://github.com/cryostatio/cryostat-core/pull/245
Not yet implemented: restarting already existing recordings, manual stop of running recordings, opening stream (download) recordings. This only enables the ability to remotely start a recording over HTTP.
> feat(api): enable dynamic JFR start

- src/main/java/io/cryostat/agent/WebServer.java
- src/main/java/io/cryostat/agent/remote/EventTemplatesContext.java
- src/main/java/io/cryostat/agent/remote/EventTypesContext.java
- src/main/java/io/cryostat/agent/remote/MBeanContext.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
- src/main/java/io/cryostat/agent/remote/RemoteContext.java
See #165
Related to #124
Adds remote endpoint ability to HTTP request Agent to stop or delete JFR by ID.
> feat(api): enable dynamic JFR stop, delete

- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
- use longs for IDs
- feat(api): implement GET /recordings/:id for streaming files
Based on #176
Fixes #178
> feat(api): implement GET /recordings/:id for streaming files

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/java/io/cryostat/agent/remote/EventTemplatesContext.java
- src/main/java/io/cryostat/agent/remote/EventTypesContext.java
- src/main/java/io/cryostat/agent/remote/MBeanContext.java
- src/main/java/io/cryostat/agent/remote/MutatingRemoteContext.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
- src/main/java/io/cryostat/agent/remote/RemoteContext.java
- src/main/resources/META-INF/microprofile-config.properties
> feat(api): mutation operations

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/resources/META-INF/microprofile-config.properties
Fixes #166
The Agent will always register as a discovery plugin and publish at least one JVM node describing itself as an Agent HTTP connection. If the Agent detects that JMX is also available on the target JVM then it will also publish a second JVM node describing itself with that JMX URL for connection.
> feat(discovery): dual HTTP+JMX registration

- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
> chore(recordings): add InvalidEventTemplateException for bad start recording requests

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/triggers/TriggerEvaluator.java
- src/main/java/io/cryostat/agent/triggers/TriggerModule.java
- src/main/resources/META-INF/microprofile-config.properties
See #217 #197 #128 
This adds handling of a new config property to allow users to specify Smart Triggers by JVM system property or environment variable in addition to the previous Agent arguments method. This is useful for cases where it may be easier to add environment variables to the target application deployment than to modify the startup script to both add an Agent and append arguments for it. For example, in my typical `vertx-fib-demo` sample application, the gradle/jib build setup also uses an additional plugin for downloading, packaging, and configuring the Agent, but it doesn't (easily) allow for adding an argument to the Agent. This is probably a pretty rare corner case, as I would expect most users who are able to add the `-javaagent` flag are also able to add the argument …
> feat(triggers): allow specification of triggers using SmallRye Config properties

- pom.xml
Fixes #261
Related to #258 
Depends on #258
I tried a quick manual test of this by setting up the Cryostat `smoketest.sh` to put a Smart Trigger on `quarkus-test-agent-1` as usual, after rebuilding it with this updated Agent JAR. The trigger was successfully activated, so it looks like CEL is working with the downgraded protobuf at least for the code paths that we currently exercise.
> build(cel): force override protobuf transitive dep used by CEL

- README.md
- src/main/java/io/cryostat/agent/insights/InsightsAgentHelper.java
- src/test/java/io/cryostat/agent/insights/InsightsAgentHelperTest.java
While it's currently possible to disable Insights support at the operator level, it would be useful to be able to do this for individual workloads. This adds a config property to do that.
Related to: https://github.com/cryostatio/cryostat/issues/1763
> feat(insights): add config parameter to opt out of Insights

- src/main/java/io/cryostat/agent/triggers/SmartTrigger.java
- src/main/java/io/cryostat/agent/triggers/TriggerParser.java
- src/test/java/io/cryostat/agent/triggers/TriggerParserTest.java
Related to #225
This PR improves whitespace handling during processing of Smart Triggers. It adds optional whitespace to the trigger grammar, and then removes all whitespaces during processing for consistency. I also added a small suite of unit tests to check this.
> fix(triggers): improve whitespace handling

- src/test/java/io/cryostat/agent/triggers/TriggerParserTest.java
Related to #253
Adds one extra test case to ensure that the `duration()` syntax accepts single-quoted values. This can be useful when deploying the Agent so the user has flexibility on where to use single and double quotes to avoid having to use escape sequences while still being able to use whitespace, or perhaps even variable interpolations, etc.
The implementation already handles this case so this is simply adding a test to catch any future regressions.
> test(smart_triggers): add test case for single-quoted duration

- .github/workflows/maven-central-release.yml
- .github/workflows/maven-publish.yaml
- pom.xml
- release.sh
See https://github.com/cryostatio/cryostat-core/pull/340
Fixes #309
> ci(central): add configurations for JReleaser publication to Maven Central

- src/main/java/io/cryostat/agent/MainModule.java
> fix(tls): use TLSv1.2

- README.md
- pom.xml
- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/AgentArgs.java
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/insights/InsightsAgentHelper.java
- src/main/java/io/cryostat/agent/triggers/TriggerEvaluator.java
- src/main/java/io/cryostat/agent/triggers/TriggerParser.java
- src/main/java/io/cryostat/agent/util/StringUtils.java
- src/test/java/io/cryostat/agent/insights/InsightsAgentHelperTest.java
- src/test/java/io/cryostat/agent/triggers/TriggerParserTest.java
Based on #224
Related to #233
This implements basic dynamic attach. The Agent can be launched as a standalone Java process like:
```bash
$ java -jar target/cryostat-agent-0.4.0-SNAPSHOT.jar 1234 # 1234 is another JVM's pid
```
This will cause the Agent process to look up PID `1234` using its Attach providers. If `1234` is found as a valid PID then the Agent process will attach to PID `1234` and attempt to load the Agent's own JAR into that running JVM, which will then bootstrap into the normal Agent launch process. If `1234` is not found then nothing is bootstrapped. Instead of `1234` the wildcard `*` can also be specified, which will lead to the Agent JAR attempting to bootstrap itself into every JVM it finds. Finally, if the PID is not specified or is `0`, then the Agent will check if …
> feat(attach): implement basic dynamic attach

- README.md
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/resources/META-INF/microprofile-config.properties
Fixes #341
- makes the webserver credential username configurable. Defaults to `user` as before, but this can be overridden if some need arises.
- makes the webserver credential password length configurable. This is always randomly generated, but the length was previously hardcoded to 24 characters. Now this can be configured, but continues to default to 24.
- expands the set of characters that can be generated for the password to include more of the ASCII symbols set. This increases password strength. Also simplifies the logic to just fill the password with any printable ASCII character, instead of trying to require at least one character from each of specific ranges first and then filling the remainder.
> feat(webserver): password length and username can be configured

- src/main/java/io/cryostat/agent/harvest/Harvester.java
> fix(harvester): ensure empty snapshots are closed

- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/WebServer.java
- src/main/java/io/cryostat/agent/harvest/Harvester.java
- src/main/java/io/cryostat/agent/triggers/TriggerParser.java
> chore(log): update log levels

- .github/workflows/ci.yaml
- .github/workflows/container-image.yml
related to: https://github.com/cryostatio/cryostat-operator/issues/791
This CI workflow builds the agent image, then packages it in the quarkus-test sample application and pushes it to the crysotat quay repo. 
example workflow in my forked -agent repo: https://github.com/mwangggg/cryostat-agent/actions/runs/8974812712
> feat(CI): Build container image

- .github/workflows/container-image.yml
- **ci(multiarch): install qemu**
- **ci(container): refactor**
Related to #390
Sample run:
https://github.com/andrewazores/cryostat-agent/actions/runs/9914757248/job/27394536931
Result:
https://quay.io/repository/andrewazores/cryostat-agent-init?tab=tags
> ci(container): fixup multiarch build, refactor

- src/main/java/io/cryostat/agent/AuthorizationType.java
- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/resources/META-INF/microprofile-config.properties
For file-read-based authorization, ie kubernetes serviceaccount token, this results in the most up-to-date value being used for HTTP client Authorization headers with each request
Fixes #428
> feat(auth): apply auth map fn on every request

- .github/workflows/maven-central-release.yml
Since https://github.com/cryostatio/cryostat-agent/pull/455 , the workflow is no longer manually callable for publishing releases to Maven Central. This attempts to re-enable that feature, so that snapshot builds get published automatically and release builds can be published with our documented manual workflow.
> ci(release): add action for manually triggering Maven Central releases

- pom.xml
- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/BuildInfo.java
- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/VersionInfo.java
- src/main/java/io/cryostat/agent/model/ServerHealth.java
- src/main/java/io/cryostat/agent/util/ResourcesUtil.java
- src/main/resources/versions.properties
- src/test/java/io/cryostat/agent/SemverTest.java
- src/test/java/io/cryostat/agent/VersionInfoTest.java
- src/test/java/io/cryostat/agent/model/ServerHealthTest.java
Fixes #504
Fixes #505
At build time, the following bits of information are recorded into resources files which are included in the distribution JAR:
- `pom.xml` `version`, ie the Agent's own version string
- `pom.xml` `cryostat.server.version.min` and `cryostat.server.version.max`, the minimum (inclusive) and maximum (exclusive) Cryostat server versions that this Agent version is expected to work with. Currently set to 4.0.0 and 5.0.0 respectively, forming the range `[4.0.0, 5.0.0)`, so that any Cryostat server version `4.y.z` should be within range. These are set as `pom.xml` properties rather than in the `microprofile-config.properties` so that they are build-time immutable.
- current git commit hash
The Agent reads its own version string and logs this at startup. It loads all of these …
> feat(versions): record own build info/version as properties, validate server version

- src/main/java/io/cryostat/agent/VersionInfo.java
- src/main/java/io/cryostat/agent/model/ServerHealth.java
- src/test/java/io/cryostat/agent/SemverTest.java
> fix(semver): handle unparseable version strings by returning UNKNOWN instead of throwing

- src/main/java/io/cryostat/agent/MainModule.java
This PR modifies the TLS server setup to not require a keystore password, but use it if provided. This makes the operator's agent auto-configuration simpler by not having to generate a secret in each target namespace, and follows cert-manager's best practices.
Fixes: #533
> feat(tls): make Keystore password optional

- src/main/java/io/cryostat/agent/ConfigModule.java
- src/main/java/io/cryostat/agent/VersionInfo.java
- src/main/java/io/cryostat/agent/util/ResourcesUtil.java
- src/main/resources/META-INF/microprofile-config.properties
Fixes #486
To test:
Agent:
```
$ ./mvnw clean spotless:apply install
$ podman build -t quay.io/$MYUSER/cryostat-agent-init:0.5.0-snapshot -f src/main/container/Dockerfile .
$ podman push quay.io/$MYUSER/cryostat-agent-init:0.5.0-snapshot
```
----
Test applications:
(directly replace `$MYUSER` in patch - variable substitution probably doesn't work here)
```diff
diff --git a/quarkus-agent/build.bash b/quarkus-agent/build.bash
index 20899a8..0209f1a 100755
--- a/quarkus-agent/build.bash
+++ b/quarkus-agent/build.bash
@@ -19,7 +19,7 @@ podman manifest create "${BUILD_IMG}:${BUILD_TAG}"
for arch in ${ARCHS:-amd64 arm64}; do
echo "Building for ${arch} ..."
-    podman build --platform="linux/${arch}" -t "${BUILD_IMG}:linux-${arch}" -f "${DIR}/src/main/docker/Dockerfile.jvm" "${DIR}"
+    podman …
```
> fix(config): config classloader strategy for different attach scenarios

- src/main/resources/simplelogger.properties
Fixes https://github.com/cryostatio/cryostat-agent/issues/530
Updates the agent logging configuration to default to WARN level. This makes sure that any problems/warnings from the agent are picked up but no additional noise.
> chore(logging): Update default logging level

- src/main/java/io/cryostat/agent/VersionInfo.java
- src/test/java/io/cryostat/agent/SemverTest.java
- src/test/java/io/cryostat/agent/VersionInfoTest.java
> fix(versioninfo): allow alternate build suffix separator characters

- src/main/java/io/cryostat/agent/Agent.java
- src/main/java/io/cryostat/agent/harvest/HarvestModule.java
- src/main/java/io/cryostat/agent/harvest/Harvester.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
1. avoid an NPE in signal handling on shutdown, which can cause the exit upload to fail
2. ensure that the recordings list reported by the Agent matches what is also seen when querying via JMX
3. rename the harvester recording to be more informative
Fixes #608 
Fixes #609
> fix(signal): avoid NPE on shutdown

- README.md
- src/main/java/io/cryostat/agent/insights/InsightsAgentHelper.java
- src/test/java/io/cryostat/agent/insights/InsightsAgentHelperTest.java
This PR retrieves the `defaultLogLevel` property for the Cryostat agent and applies it to the Insights agent's shaded logger. This can still be overriden by the `RHT_INSIGHTS_JAVA_DEBUG` config parameter to force debug logging for Insights only.
Fixes: https://github.com/cryostatio/cryostat-operator/issues/1090
> fix(insights): inherit log level from Cryostat agent

- pom.xml
Following the sunset of OSSRH, Sonatype recommends using their [Staging API](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/) to migrate to the Central Publisher Portal to maintain compatibility with existing tools.
Fixes: #669
> build(maven): update Maven Central publishing URLs

- src/main/java/io/cryostat/agent/remote/InvokeContext.java
Related to https://github.com/cryostatio/cryostat/issues/135
Adds the ability to capture thread dumps to the agent's mbean-invoke endpoint. The original implementation of the endpoint is already fairly flexible, essentially acting as a wrapper around the mbean.invoke method, so we just need to extend the check for valid/supported operations, and add a further check if we're doing a thread dump so it can be written to the response body as-is.
Currently supports the threadPrint operation but leaves an opening for the threadDumpToFile operation to be supported later if necessary. Note that the format of threadDumpToFile isn't supported by existing support tooling so it won't work for the purposes of the linked issue, only threadPrint.
Opening as Draft until the other pieces of the feature …
> feat(diagnostics): Add thread dump capturing to diagnostics endpoint

- src/main/java/io/cryostat/agent/remote/InvokeContext.java
Hi,
Quick fix to only check the paremeters for a request ID when a heap dump is requested. Fixes an issue that occurs when triggering a thread dump/gc since they have no need to pass on that ID and/or don't have one to begin with.
> fix(diagnostics): Only check parameters for requestid for heap dumps

- src/main/java/io/cryostat/agent/triggers/TriggerParser.java
Related to: https://github.com/cryostatio/cryostat-agent/issues/672
I'm unable to reproduce the original issue, however the log warning can be corrected. This PR corrects the log warning to get the value of the Optional rather than using a direct toString. 
To test:
- Pull and build this PR
- Launch a sample application with the built version of the agent
- Specify a path that doesn't exist (CRYOSTAT_AGENT_SMART_TRIGGER_CONFIG_PATH: foo)
- Check that a sensible message gets logged (WARN io.cryostat.agent.triggers.TriggerParser - Configuration directory foo doesn't exist or is missing permissions)
> fix(triggers): Fix triggerParser warning to use optional value
