cryostatio/cryostat-agent

- .github/release-drafter.yml
- .github/workflows/ci.yaml
- .github/workflows/dependent-issues.yml
- .github/workflows/linked-issue.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/publish.yaml
- .github/workflows/release-drafter.yml
- .github/workflows/semantic-pr.yml
- pom.xml
Fixes #1
reference for publishing action: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
> ci(init): set up CI configs

- .github/workflows/ci.yaml
- .github/workflows/maven-publish.yaml
- README.md
- pom.xml
- Target JDK 11
- use JDK11 in CI
Fixes #10
Depends on #12
> chore(jdk): use JDK 11

- .github/CODEOWNERS
- .github/dependabot.yml
- pom.xml
- src/main/java/io/cryostat/agent/MainModule.java
> ci(dependabot): add config

- .mergify.yml
- pom.xml
Related to https://github.com/cryostatio/cryostat/issues/1459
> build(config): update pom and add mergify for 2.3 release

- pom.xml
> chore(pom): correct project name

- src/main/java/io/cryostat/agent/WebServer.java
> fix(webserver): use nonblocking SecureRandom

- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
> fix(recordings): handle null maxAge

- pom.xml
Related to: https://github.com/cryostatio/cryostat/issues/1459
> chore(version): bump version to 0.2.3-SNAPSHOT

- .github/workflows/ci.yaml
> ci(pr-targets): use `safe-to-test` only on PR and trigger on label/unlabel

- .github/workflows/check-labels.yml
- .github/workflows/ci.yaml
- .github/workflows/labeler.yml
> chore(CI): Update CI configs

- src/main/java/io/cryostat/agent/remote/MBeanContext.java
Fixes https://github.com/cryostatio/cryostat-core/issues/218
> fix(mbean): suppress warning message if BootClassPath unsupported

- README.md
> chore(readme): add badges to readme

- pom.xml
Related to: https://github.com/cryostatio/cryostat/pull/1662
> build(pom): restore dagger compiler property

- .github/workflows/ci.yaml
> ci(jdk): also test on JDK 21

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
See https://github.com/cryostatio/cryostat-reports/pull/140
> build(mvn): add mvn wrapper

- .github/labeler.yml
- .mergify.yml
- pom.xml
Related to https://github.com/cryostatio/cryostat/issues/1695
> chore(release): prepare for cryostat 2.4.0 release

- src/main/java/io/cryostat/agent/Registration.java
- src/main/java/io/cryostat/agent/model/PluginInfo.java
Depends on https://github.com/cryostatio/cryostat/pull/1520
Related to https://github.com/cryostatio/cryostat/issues/1763
> feat(registration): receive platform env map from server on registration

- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/FlightRecorderHelper.java
- src/test/java/io/cryostat/agent/FlightRecorderHelperTest.java
> fix(agent): accept 'ALL' event template in recording start

- pom.xml
fixes: #279 
I also replaced the deprecated OperatingSystemMXBean methods.
> fix(pom): remove classpath manifest entry

- src/main/java/io/cryostat/agent/harvest/HarvestModule.java
- src/main/java/io/cryostat/agent/harvest/Harvester.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
See https://github.com/cryostatio/cryostat3/pull/342#issuecomment-2054394673
> fix(remote): improve response status codes, don't include harvester snapshots in listing

- .github/workflows/container-image.yml
> chore(ci): fix CI failure

- pom.xml
- src/main/java/io/cryostat/agent/MainModule.java
- src/main/java/io/cryostat/agent/model/MBeanInfo.java
- src/main/java/io/cryostat/agent/remote/MBeanContext.java
- src/main/java/io/cryostat/agent/remote/RecordingsContext.java
See https://github.com/cryostatio/cryostat-core/issues/416
Depends on https://github.com/cryostatio/cryostat-core/pull/423
> chore(libcryostat): clean up to use libcryostat dependency

- .github/workflows/maven-central-release.yml
- pom.xml
See #441
See cryostatio/cryostat-core#382
> ci(jreleaser): enable publishing with libcryostat -SNAPSHOT dependency

- .github/workflows/ci.yaml
- .github/workflows/maven-central-publish.yml
- release-snapshot.sh
> ci(snapshot): publish snapshot builds on merge to main

- .github/workflows/ci.yaml
- .github/workflows/pr-ci.yaml
> ci(build): split CI for PRs from pushes

- pom.xml
See https://github.com/cryostatio/cryostat-agent/pull/462
> build(deps): bump org.slf4j.version from 2.0.12 to 2.0.13

- pom.xml
See https://github.com/cryostatio/cryostat-agent/pull/445
> build(deps): bump io.smallrye.config.version from 3.4.3 to 3.5.4

- .github/workflows/ci.yaml
- .github/workflows/container-image.yml
- .github/workflows/maven-central-publish.yml
- .github/workflows/maven-publish.yaml
- .github/workflows/pr-ci.yaml
- pom.xml
- release-snapshot.sh
Related to https://github.com/cryostatio/cryostat-agent/pull/453
> ci(snapshots): set Central snapshots repository for libcryostat dependency only when publishing a snapshot

- src/main/java/io/cryostat/agent/CryostatClient.java
See https://github.com/cryostatio/cryostat/pull/609
Fixes https://github.com/cryostatio/cryostat-agent/issues/481
> fix(http): ensure HTTP response body streams are not prematurely closed

- src/main/java/io/cryostat/agent/CryostatClient.java
- src/main/java/io/cryostat/agent/insights/InsightsAgentHelper.java
- src/main/java/io/cryostat/agent/model/KeyValue.java
- src/main/java/io/cryostat/agent/model/MBeanInfo.java
- src/main/java/io/cryostat/agent/model/PluginInfo.java
- src/test/java/io/cryostat/agent/insights/InsightsAgentHelperTest.java
depends on: [https://github.com/cryostatio/cryostat/pull/584](https://github.com/cryostatio/cryostat/pull/584)
part of: [https://github.com/cryostatio/cryostat/issues/550](https://github.com/cryostatio/cryostat/issues/550)
> feat(API): update Agent to use V4 endpoints

- src/main/java/io/cryostat/agent/model/KeyValue.java
Tested in OpenShift with this PR and it appears to fix the issue.
Fixes: #510 
Related to #469
> fix(json): add no-arg constructor and setters to KeyValue

- src/main/java/io/cryostat/agent/FlightRecorderHelper.java
Related to https://github.com/cryostatio/cryostat/issues/548
Depends on https://github.com/cryostatio/cryostat-core/pull/486
> chore(eventtemplates): use libcryostat TemplateType

- src/main/container/Dockerfile
Related to https://github.com/cryostatio/cryostat/issues/650
> chore(container): upgrade init container to UBI9

- src/main/container/Dockerfile
> fix(container): set USER in Dockerfile

- src/main/resources/simplelogger.properties
Fixes https://github.com/cryostatio/cryostat-agent/issues/624
> fix(log): set default log stream to stdout

- pom.xml
> build(deps): bump com.fasterxml.jackson:jackson-bom from 2.18.3 to 2.18.4

- pom.xml
This reverts commit 7526e2d351e28d3092e62b3e696da5f1f9636810.
> Revert "build(deps): bump io.smallrye.config.version from 3.13.4 to 3.14.0 (#710)"
